### ISSUE TITLE
Глоссарий

### ISSUE THREAD

**Issue by AnnMalofeeva** [SorokinStanislav/UPP#11]
[Lazarev_Glossary.v1.3_ question.docx](https://github.com/SorokinStanislav/UPP/files/9291/Lazarev_Glossary.v1.3_.question.docx)

**Comment by AnnMalofeeva** [comment]
еще надо что-то с личным кабинетом решить, но это чуть позже.

**Comment by SorokinStanislav** [comment]
Личный кабинет в стадии продумывания в структуре интерфейса. Так что ждем, и далее согласованно с этим пишем.
Помимо этого увидел неопознанный термин в требованиях.
[Lazarev_Glossary.v1.3_.question.docx](https://github.com/SorokinStanislav/UPP/files/10953/Lazarev_Glossary.v1.3_.question.docx)

**Comment by LazarevSergey** [comment]
окей подправлю

**Comment by SorokinStanislav** [comment]
Добавить "Проверка задачи"

**Comment by LazarevSergey** [comment]
[Lazarev_Glossary.v1.4.docx](https://github.com/SorokinStanislav/UPP/files/11200/Lazarev_Glossary.v1.4.docx)

**Comment by SorokinStanislav** [comment]
И вечный бой, покой нам только снится...
[Lazarev_Glossary.v1.4.docx](https://github.com/SorokinStanislav/UPP/files/11250/Lazarev_Glossary.v1.4.docx)

**Comment by LazarevSergey** [comment]
И пусть ничто не потревожит сны...
[Lazarev_Glossary.v1.5.docx](https://github.com/SorokinStanislav/UPP/files/11264/Lazarev_Glossary.v1.5.docx)

**Comment by SorokinStanislav** [comment]
И нет конца! Мелькают версты, кручи...

**Comment by SorokinStanislav** [comment]
И нет конца! Мелькают версты, кручи...
[Lazarev_Glossary.v1.5.docx](https://github.com/SorokinStanislav/UPP/files/11298/Lazarev_Glossary.v1.5.docx)

**Comment by LazarevSergey** [comment]
Останови! ... Закат в крови!
[Lazarev_Glossary.v1.6.docx](https://github.com/SorokinStanislav/UPP/files/11302/Lazarev_Glossary.v1.6.docx)

**Comment by SorokinStanislav** [comment]
коммит
