### ISSUE TITLE
Requirements_mistakes

### ISSUE THREAD

**Issue by AnnMalofeeva** [SorokinStanislav/UPP#12]
Посмотрите.
[Requirements_v3_3_Aseev_Malofeeva.docx](https://github.com/SorokinStanislav/UPP/files/9292/Requirements_v3_3_Aseev_Malofeeva.docx)

**Comment by SorokinStanislav** [comment]
Остался небольшой идеологический вопрос. Пока не знаю точный на него ответ, но попытался раскрыть в файле. 
[Requirements_v3_3_Aseev_Malofeeva.docx](https://github.com/SorokinStanislav/UPP/files/10947/Requirements_v3_3_Aseev_Malofeeva.docx)

**Comment by AnnMalofeeva** [comment]
[Requirements_v3_3_Aseev_Malofeeva.docx](https://github.com/SorokinStanislav/UPP/files/11388/Requirements_v3_3_Aseev_Malofeeva.docx)
