### ISSUE TITLE
Структура Web-интерфейса

### ISSUE THREAD

**Issue by LazarevSergey** [SorokinStanislav/UPP#13]
Стас, мы с Мишей сделали общее задание и дополнили его своими индивидуальными заданиям. Посмотри и прокомментируй.
[Structure_Of_Web-Interface_v1.1_Aseev_Lazarev.docx](https://github.com/SorokinStanislav/UPP/files/10914/Structure_Of_Web-Interface_v1.1_Aseev_Lazarev.docx)

**Comment by SorokinStanislav** [comment]
Основные замечания:
1. Не вижу четкую структуру перехода с одной страницы на другую.
2. Мне кажется, не все страницы расписаны.
3. Не соблюдение требований

Жду исправлений!
[Structure_Of_Web-Interface_v1.1_Aseev_Lazarev.docx](https://github.com/SorokinStanislav/UPP/files/10937/Structure_Of_Web-Interface_v1.1_Aseev_Lazarev.docx)

**Comment by LazarevSergey** [comment]
[Structure_Of_Web-Interface_v1.2_Aseev_Lazarev.docx](https://github.com/SorokinStanislav/UPP/files/11060/Structure_Of_Web-Interface_v1.2_Aseev_Lazarev.docx)

Все указанные выше замечания учтены.

**Comment by SorokinStanislav** [comment]
Добавить "Проверка задачи"
