### ISSUE TITLE
КМБД 

### ISSUE THREAD

**Issue by mrudanov** [SorokinStanislav/UPP#14]
Составили КМБД (ER-диаграмму) в СильверРане. Консультировались с Владом, вроде важные аспекты учтены. Из основных изменений - связь UserRatingInSection преобразовали в сущность, по причине того, что связь SubmissionChangeUserRating должна связывать решение пользователя и его рейтинг в конкретной секции, но ранее не существовало сущности, отвечающей за рейтинг (эта информация хранилась внутри связи).
Если что необходимо скорректировать, пиши.
![kmbd_picture](https://cloud.githubusercontent.com/assets/11590187/10411785/40b05a8e-6f7a-11e5-8681-90a9b8e34cdd.png)

**Comment by mrudanov** [comment]
Соответственно, при добавлении данной сущности, мы добавили связи UserHasRating и RatingInSection.

**Comment by SorokinStanislav** [comment]
Все входимости посмотрел, вроде противоречий нет. 
Владу следует дополнить файл описания КМБД новой сущностью и связями.

**Comment by SorokinStanislav** [comment]
В сущность Пользователь добавить Имя, Фамилия, почту, город, страну - и Мише с Лешей в схему, и Владу в описание

**Comment by bdzl** [comment]
Почему у Вас во всех сущностях есть Id, а в UserRatingInSection нет?

**Comment by bdzl** [comment]
Мощность между User и UserHasRating поправить на (0, N)

**Comment by bdzl** [comment]
UserPickedTask должна быть связана также и с Section, поскольку это связь означает, что пользователь открыл некоторую задачку по некоторому разделу. И мощность там соответствующая. С разделом - (0, н). С юзером - (0, н). С задачей - (0, н)

**Comment by bdzl** [comment]
Кстати, наверное, лучше ограничение целостности на тот факт, что каждый раздел содержит хотя бы одну задачу, добавить в мощностные характеристики. а именно, связь TaskInSection связывает Section мощностью (1, n)

**Comment by bdzl** [comment]
Косметическое замечание: почему USER не User?

**Comment by bdzl** [comment]
У нас там у Submission есть статус, который хранится в связи UserSendSubmission. Он указывает этап проверки посылки "Компилируется, работает на тесте н, завершено тестирование" --- как-нибудь так. Вердикт пользователь получает только на последний момент, когда завершено тестирование. Поэтому мощность между Submission и  RecievedVerdict должна быть (0, 1)

**Comment by mrudanov** [comment]
Влад, все понял, поправим. Есть еще один вопросик, по поводу того, как учесть те задачи, которые могут просматривать неавторизованные пользователи? Стоит ли добавить для этого специальный статус к сущности Task?

**Comment by bdzl** [comment]
И давайте сущность UserRatingInSection назовем попроще. Получается какое-то дублирование с RatingInSection. Предлагаю переименовать UserRatingInSection в Rating.

p.s. идейно задача должна иметь рейтинг в каждом из разделов, как и пользователь. но пока остановимся на таком варианте, на следующем витке доделаем, потому что сейчас и без этого много дыр, переделывать же не только БД, а требования и все остальное.

**Comment by bdzl** [comment]
ReceivedVerdict не нужно связывать c Task. Это лишние связи. Всю информацию о вердикте можно получить через посылку и ее связи.

**Comment by bdzl** [comment]
Текстовое описание КМБД сделал

**Comment by bdzl** [comment]
Имя, фамилия, почта, город, страна - мы, как я понял, решили пока не торопиться. Если такие данные будут необходимы, потом добавим

**Comment by bdzl** [comment]
Пусть пока неавторизованные пользователи не могут видеть задачки. На следующем витке добавим какие-нибудь TaskExample

**Comment by bdzl** [comment]
Постарайтесь придерживаться текстового описания. А если что-то идет вразрез, поправьте сами, либо скажите мне. Хочется, чтобы описание и схема как-то были связаны все-таки.

Спасибо Вам ребята, хорошая работа.

**Comment by mrudanov** [comment]
![cmdb](https://cloud.githubusercontent.com/assets/11590187/10415982/b039c95e-700a-11e5-930e-10891da2e5ec.jpg)

**Comment by mrudanov** [comment]
Вот исправленная версия, вроде все учли,
