### ISSUE TITLE
Интерфейс решения задачи

### ISSUE THREAD

**Issue by SorokinStanislav** [SorokinStanislav/UPP#16]
[task_interface.docx](https://github.com/SorokinStanislav/UPP/files/11317/task_interface.docx)
В вопросе с рисунком, мб я не помню, и такое было в старых тербованиях, либо это не было ранее зафиксировано вообще. Но я что-то помню разговоры об этом. Напомни, что там было, если не помнишь, надо у Влада или Жени уточнить.

**Comment by LazarevSergey** [comment]
Действительно данный момент в требованиях не нашел
[task_interface.docx](https://github.com/SorokinStanislav/UPP/files/11322/task_interface.docx)

**Comment by SorokinStanislav** [comment]
[task_interface (1).docx](https://github.com/SorokinStanislav/UPP/files/11338/task_interface.1.docx)
Еще чуть-чуть исправить

**Comment by SorokinStanislav** [comment]
Пару косяков еще поправить.
[task_interface (1).docx](https://github.com/SorokinStanislav/UPP/files/11341/task_interface.1.docx)

**Comment by LazarevSergey** [comment]
[task_interface.1.docx](https://github.com/SorokinStanislav/UPP/files/11366/task_interface.1.docx)
