### ISSUE TITLE
Страница управления модератора

### ISSUE THREAD

**Issue by PetrovAnatoly** [SorokinStanislav/UPP#17]
[Petrov_moderator_page.docx](https://github.com/SorokinStanislav/UPP/files/11320/Petrov_moderator_page.docx)

**Comment by SorokinStanislav** [comment]
[Petrov_moderator_page.docx](https://github.com/SorokinStanislav/UPP/files/11324/Petrov_moderator_page.docx)

**Comment by PetrovAnatoly** [comment]
[Petrov_moderator_page.docx](https://github.com/SorokinStanislav/UPP/files/11325/Petrov_moderator_page.docx)

**Comment by PetrovAnatoly** [comment]
[Petrov_admin_page.docx](https://github.com/SorokinStanislav/UPP/files/11337/Petrov_admin_page.docx)

**Comment by SorokinStanislav** [comment]
[Petrov_admin_page.docx](https://github.com/SorokinStanislav/UPP/files/11383/Petrov_admin_page.docx)
Поправить ошибки в обоих документах
[Petrov_moderator_page (1).docx](https://github.com/SorokinStanislav/UPP/files/11382/Petrov_moderator_page.1.docx)
