### ISSUE TITLE
Требования первого витка

### ISSUE THREAD

**Issue by bdzl** [SorokinStanislav/UPP#20]
1. Мы либо не пишем пока, что система присваивает каждой задаче рейтинг, либо пишем, но говорим, что рейтинг - оценка сложности задачи относительно других, или что-то более разумное.

Вроде в остальном съедобно, только надо убедиться, что мы покрыли все функц нефункц требования первого витка

**Comment by SorokinStanislav** [comment]
Исправили понятие задачи в глоссарии
