### ISSUE TITLE
Основное меню и страница личных данных.

### ISSUE THREAD

**Issue by LazarevSergey** [SorokinStanislav/UPP#23]
[Description_of_general_menu_&_page_private_data.docx](https://github.com/SorokinStanislav/UPP/files/15489/Description_of_general_menu_._page_private_data.docx)

**Comment by SorokinStanislav** [comment]
Посмотри на замечания
[Description_of_general_menu_._page_private_data.docx](https://github.com/SorokinStanislav/UPP/files/15651/Description_of_general_menu_._page_private_data.docx)

**Comment by LazarevSergey** [comment]
[Description_of_general_menu_&_page_private_data.docx](https://github.com/SorokinStanislav/UPP/files/15708/Description_of_general_menu_._page_private_data.docx)

**Comment by SorokinStanislav** [comment]
Все ок. Можешь закоммитить и распечатать.
