### ISSUE TITLE
Страница выбранного раздела и страница авторизации

### ISSUE THREAD

**Issue by PetrovAnatoly** [SorokinStanislav/UPP#25]
[selected_section_page.docx](https://github.com/SorokinStanislav/UPP/files/15656/selected_section_page.docx)

**Comment by PetrovAnatoly** [comment]
[login_page.docx](https://github.com/SorokinStanislav/UPP/files/15665/login_page.docx)

**Comment by bdzl** [comment]
Страница выбранного раздела
Наверное, ты неправильно понял нас. Это вина не твоя, а тех, кто объяснял.

На этой странице должно быть сверху-вниз название раздела; кнопка "продолжить решение / последней задачи / подобрать новую задачу", которая принимает одно из этих 2х значений в зависимости от того, выбрана ли задача пользователем по этому разделу, или нет; краткое описание раздела; тестовая задачка (классическая для выбранного раздела), а именно, условие, решение

Логин
Все хорошо

**Comment by PetrovAnatoly** [comment]
[selected_section_page.docx](https://github.com/SorokinStanislav/UPP/files/15717/selected_section_page.docx)

**Comment by SorokinStanislav** [comment]
Все хорошо. Коммит. И завтра в мифяге оба документа распечатать.
