### ISSUE TITLE
Description of the personal account

### ISSUE THREAD

**Issue by ghost** [SorokinStanislav/UPP#26]
[Description_of_the_personal_account.docx](https://github.com/SorokinStanislav/UPP/files/15676/Description_of_the_personal_account.docx)

**Comment by SorokinStanislav** [comment]
ОК

**Comment by bdzl** [comment]
1) Предложение сделать, как на codeforces.com http://codeforces.com/profile/bdzl
Почему? Потому что 3 - 5 - 10 кнопочек, расположенных в центре экрана, очень привлекают внимание, занимают лишний урл. Предлагается сделать их в виде дополнительной менюшки, открывающейся при заходе на любую страничку личного кабинета. По дефолту открыта вкладка подменюшки, где описаны личные данные, например. Можно переходить из одной вкладки в другую. Подменюшка расположены чуть ниже основной, маленького размера. На кодфорсес, по-моему, очень хорошо это реализовано. Пример кинул

2) Если есть другие, более интересные предложения - готов рассмотреть с радостью
