### ISSUE TITLE
Страница регистрации и главная страница

### ISSUE THREAD

**Issue by SorokinStanislav** [SorokinStanislav/UPP#27]
https://gyazo.com/f81fa0df551336d66e5601a821c973de - регистрация
https://gyazo.com/2942fbdf303c30c50f30cf297917b8c0 - главная

**Comment by bdzl** [comment]
Регистрация
1) У нас в системе на данном витке нет e-mail, подтверждения через e-mail, соответственно, тоже нет

2) Прилагаемая инструкция по регистрация совсем лишняя. Достаточно маленького указания выше формочки с данными "Для регистрации в системе укажите Ваши данные", ниже маленьким шрифтом сообщение о том, что звездочкой помечены необходимые поля. После нажатия на кнопку подтверждения должно появляться окошко в стиле "Поздравляем! Вы успешно зарегистрировались в системе. Ваш логин: бла-бла"

3) Все менюшки в регистрации не нужны, для этого у нас должно быть единое меню на все странички с одним интерфейсом

**Comment by bdzl** [comment]
Главная
1) Кем и как создан сайт никого не интересует, как правило. Нужно маленьким шрифтом далеко внизу. Причем разместить это лучше всего на каждой страничке

2) Меню, опять же, не нужно 

3) Описание, кажется, приятнее вынести в отдельную страничку и ссылочку на эту страничку в главную менюшку. На этой страничке так же могут быть часто задаваемые вопросы и т.п.  А на главной страничке разместить какой-нибудь постер, например, как тут: https://codefights.com Причем при клике на Prove It появляется иконка с тестовыми заданиями
