### ISSUE TITLE
Макет страницы выбора раздела

### ISSUE THREAD

**Issue by alex110010** [SorokinStanislav/UPP#28]
[Zavarzin_veb_maket_sections.docx](https://github.com/SorokinStanislav/UPP/files/15718/Zavarzin_veb_maket_sections.docx)

**Comment by bdzl** [comment]
1) Овервью надо убрать. Вместо этого предлагается в правом окошке отображения инфы написать две иструкции маленьким шрифтом сверху "наведите на название раздела, чтобы прочитать доп. информацию; чтобы перейти на страницу раздела, нажмите на его название", а ниже при наведении на раздел появляется информация в этом же блоке большим шрифтом. информация краткая.

2) эта веб-страница не должна содержать никакую новостную ленту. в описаниях веб-страниц такого нет. в первом витке у нас вообще нет новостной ленты, советую ознакомиться с документами, прежде чем что-то делать. в целом, я вообще не помню, чтобы мы на собраниях упоминали новостную ленту. их тоже полезно посещать
