### ISSUE TITLE
Глоссарий

### ISSUE THREAD

**Issue by SorokinStanislav** [SorokinStanislav/UPP#4]
Доделать 27.09.15 23:0
[Glossary.docx](https://github.com/SorokinStanislav/UPP/files/3045/Glossary.docx)
0.

**Comment by LazarevSergey** [comment]
Исправил, добавил. Стас, тестирования в том ключе, в котором ты думал в требованиях обнаружено не было.
[Glossary.docx](https://github.com/SorokinStanislav/UPP/files/3181/Glossary.docx)

**Comment by SorokinStanislav** [comment]
Ок. Заливай.
