### ISSUE TITLE
Архитектура системы

### ISSUE THREAD

**Issue by SorokinStanislav** [SorokinStanislav/UPP#5]
Необходимо нарисовать более подробную схему архитектуры проекта, как рисовал Влад, однако может и в нее что-либо добавить. Но главное показать связь с другими логическими модулями нашего проекта, такими как: алгоритмы подбора задач, изменения рейтинга, базы задач. В общем абсолютно всех модулей, указанных в календарном плане в блоке "Разработка". 
Нужно оформить в виде некоторой диаграммы наверное без каких-либо нотаций, но использовать какой-либо графический редактор, будь то Visio, или Dia, или еще что-то. Главное  - чтобы после одного простого объяснения была понятна работа всей системы.

**Comment by EAkimutin** [comment]
Сделал схему проверки задач. Поскольку я сам ещё не представляю, как будет происходить подбор задач, в схеме не представлен алгоритм подбора задач и всё с этим связанное. Никаких стандартов не придерживался, старался не загромождать схему лишними подробностями. Исходник сюда не загружается, поэтому смотрим PDF.

[Akimutin_Diagram.pdf](https://github.com/SorokinStanislav/UPP/files/7191/Akimutin_Diagram.pdf)

**Comment by SorokinStanislav** [comment]
Мне все понравилось. Твоя задача  будет по-быстрому это начертить и рассказать на семинаре. Commit

**Comment by SorokinStanislav** [comment]
Считаю замечания влада компетентными, поэтому, думаю, дальнейшее согласование сначала должно быть с ним. Затем уже сюда отправляй.
