### ISSUE TITLE
funktsionaltye trebovaniya

### ISSUE THREAD

**Issue by mrudanov** [SorokinStanislav/UPP#6]
[Funktsionalnye_trebovania_Rudanov_Petrov.docx](https://github.com/SorokinStanislav/UPP/files/7184/Funktsionalnye_trebovania_Rudanov_Petrov.docx)

**Comment by SorokinStanislav** [comment]
Исправить очевидные замечания и подумать, как решить менее очевидные. Чем раньше, тем лучше! 
[Funktsionalnye_trebovania_Rudanov_Petrov.docx](https://github.com/SorokinStanislav/UPP/files/7193/Funktsionalnye_trebovania_Rudanov_Petrov.docx)

**Comment by mrudanov** [comment]
Привет, исправил ошибки. Извиняюсь за такое количество нелепых лексических недочетов.
В документе зеленым цветом выделил спорные места, которые оставил на свое усмотрение, также, указал причину, почему считаю именно так. Если кажется, что надо поменять эти места, говори.
Попроси, плз, Сережу добавить в глоссарий Личный кабинет.

[Funktsionalnye_trebovania_Rudanov_Petrov.docx](https://github.com/SorokinStanislav/UPP/files/7216/Funktsionalnye_trebovania_Rudanov_Petrov.docx)

**Comment by SorokinStanislav** [comment]
Уже попросил.
Исправляй и коммить сразу.
[Funktsionalnye_trebovania_Rudanov_Petrov (1).docx](https://github.com/SorokinStanislav/UPP/files/7220/Funktsionalnye_trebovania_Rudanov_Petrov.1.docx)

**Comment by mrudanov** [comment]
Стас, проблемы с гитом, закомить, плз, если не сложно)
[Funktsionalnye_trebovania_Rudanov_Petrov.docx](https://github.com/SorokinStanislav/UPP/files/7224/Funktsionalnye_trebovania_Rudanov_Petrov.docx)
