### ISSUE TITLE
Глоссарий.

### ISSUE THREAD

**Issue by LazarevSergey** [SorokinStanislav/UPP#7]
[Lazarev_Glossary(v1.1).docx](https://github.com/SorokinStanislav/UPP/files/7187/Lazarev_Glossary.v1.1.docx)
Народ дополнил слово "Соединение" прошу знатоков его проверить, чуть-чуть подправил "Набор тестов". Убедительная просьба, ребят напишите, чего не хватает на ваш взгляд. Напоминаю, что "термины" должны быть из предметной области.

**Comment by SorokinStanislav** [comment]
На исправление.
[Lazarev_Glossary.v1.1.docx](https://github.com/SorokinStanislav/UPP/files/7195/Lazarev_Glossary.v1.1.docx)

**Comment by LazarevSergey** [comment]
[Lazarev_Glossary(v1.2).docx](https://github.com/SorokinStanislav/UPP/files/7211/Lazarev_Glossary.v1.2.docx)
Ожидаю оставшиеся требования

**Comment by SorokinStanislav** [comment]
На исправление.
[Lazarev_Glossary.v1.2.docx](https://github.com/SorokinStanislav/UPP/files/7212/Lazarev_Glossary.v1.2.docx)

**Comment by LazarevSergey** [comment]
[Lazarev_Glossary(v1.3).docx](https://github.com/SorokinStanislav/UPP/files/7270/Lazarev_Glossary.v1.3.docx)
Подправил. Прочитал новые функциональные и нефункциональные требования, нового ничего не увидел. Добавить, на мой взгляд, нечего.

**Comment by SorokinStanislav** [comment]
Добавил еще чуть-чуть, что вчера ночью добавили. Сам закоммитил.
