### ISSUE TITLE
Замечания к Akimutin_Diagram

### ISSUE THREAD

**Issue by bdzl** [SorokinStanislav/UPP#9]
1) Рейтинг задачи хранится в БД, не относится к Банку Задач (БЗ).
2) БД надо назвать БД, а не БД с данными о пользователях.
3) Рейтинг меняется не только у пользователя, но и у задачи. 
4) Зачем-то есть описание работы чекера, но чекер в основной схеме нигде не используется. 
Нужно добавить описание работы тестирующей системы. То, как она использует чекер. Чтобы там было явно видно, что тестов много, что проверка производится последовательно на каждом тесте независимо при помощи чекера. Вердикт тестирующей системы = объединение вердиктов чекера на всех тестах.
5) Исходя из пункта 4, сам чекер можно не описывать. Из описания работы тестирующей системы будет очевидно, как работает чекер.
6) Вспомогательные материалы в Задаче. Непонятно, что это. Заменить на "Авторское решение". Добавить туда же понятие "Разбор решения".

**Comment by SorokinStanislav** [comment]
"Авторское решение" в нашей системе будет называться "Предлагаемое решение"
